### PR TITLE
Add Dockerfile for Swift

### PR DESCRIPTION
**Pull request by Zollerboy1**

### CODE REVIEW

**Comment by umgefahren** [comment]
Consider building the application in a different counter from where you run it.

**Review by tectrixer — COMMENTED** [review]
Well, I still cannot build the binary, as there is no version for arm64. But as far as I understood that's not fixable, right?

**Review by umgefahren — APPROVED** [review]

**Comment by Zollerboy1** [comment]
@umgefahren I would definitely run in a different container but I just can't get it to work. In principle, it should be possible by passing Swift the `-static-executable` flag, but it just doesn't want to run when I do that.

**Comment by Zollerboy1** [comment]
@umgefahren What about this?

**Review by umgefahren — APPROVED** [review]
Seems good to me

**Pull request merged**
