### PR TITLE
Commit Swift Dockerfile

### PR DESCRIPTION
**Pull request by umgefahren**
Added Dockerfile for Swift

### CODE REVIEW

**Comment by tectrixer** [comment]
I would recommend to switch to scratch or alpine for the final image and to statically link the binary.

That's also what vypxl required from my rust dockerization.

**Comment by umgefahren** [comment]
Linking against MUSL is not possible in the Swift Compiler. Thus Alpine is not supported.

**Comment by umgefahren** [comment]
Maybe it is possible, however there is no official docker image.

**Comment by tectrixer** [comment]
Ahh, ok, then I guess this is perfect

**Comment by Zollerboy1** [comment]
I'm getting an error that it doesn't find the swift executable. It works when I change to swift:latest.

**Comment by tectrixer** [comment]
Btw, I just tried to run it and I get the following error:
`failed to solve with frontend dockerfile.v0: failed to create LLB definition: circular dependency detected on stage: builder`
Is that because I am not doing something correctly?

**Comment by Zollerboy1** [comment]
Also, since the swift executable isn't statically linked, you cannot just copy it over to another image, because it needs dynamically linked libraries like `Foundation`. Also, `RUN debian:slim` is just wrong on multiple levels (it would be `FROM`, not `RUN` and there is no tag called `debian:slim`, you have to use something like `debian:stable-slim`).

**Comment by Zollerboy1** [comment]
> Btw, I just tried to run it and I get the following error:
> `failed to solve with frontend dockerfile.v0: failed to create LLB definition: circular dependency detected on stage: builder`
> Is that because I am not doing something correctly?

Try

```bash
DOCKER_BUILDKIT=0 docker build -t bench-swift .
```

**Comment by tectrixer** [comment]
Thx, that worked! What does this environment variable do?

Btw, I've now got another error, but this one does not seem to be avoidable: `no matching manifest for linux/arm64/v8 in the manifest list entries`

**Comment by Zollerboy1** [comment]
Yeah, as I said, there is no tag named `debian:slim`. Try `debian:stable-slim` instead. But it will still not work then, as only the executable is copied over.

**Review by Zollerboy1 — COMMENTED** [review]
This Dockerfile definitely doesn't work. I had already written one on my branch, so I created a new pull request (#19) and will close this one.

**Comment by umgefahren** [comment]
Do it

**Comment by umgefahren** [comment]
> Also, since the swift executable isn't statically linked, you cannot just copy it over to another image, because it needs dynamically linked libraries like `Foundation`. Also, `RUN debian:slim` is just wrong on multiple levels (it would be `FROM`, not `RUN` and there is no tag called `debian:slim`, you have to use something like `debian:stable-slim`).

Thanks for clarifying

**Pull request closed without merging**
