### PR TITLE
Implement full spec in Deno

### PR DESCRIPTION
**Pull request by satoqz**
The Deno implementation now implements the entire spec (i hope lol)

### CODE REVIEW

**Review by tectrixer — APPROVED** [review]
I did not test all commands, but it looks good to me. Nice that you implemented so much in such little time :)

**Comment by tectrixer** [comment]
@umgefahren If its fine for you I'll merge to main

**Comment by umgefahren** [comment]
Feel free to do so

**Comment by satoqz** [comment]
i'll merge it later, i still want to make the dockerfile work properly with aarch64 somehow

**Comment by Zollerboy1** [comment]
Just wanted to try this out but both on my Mac and on my server running Ubuntu I'm getting the error message `standard_init_linux.go:228: exec user process caused: no such file or directory` when I'm trying to start the docker container (`docker build -t bench-deno .` and then `docker run --name bench-deno -tp 8080:8080 bench-deno` on branch `deno_dev`).

**Comment by satoqz** [comment]
yeah i got the same thing on ubuntu x86 earlier..
sadly deno is still a mess when trying to use it with docker, alpine and alike

**Comment by satoqz** [comment]
@Zollerboy1 try again if you don't mind, it's a bit hacky now but for me it works on both amd64 and arm64 which is what i was going for :)

**Pull request merged**
