### PR TITLE
Add script to run all benchmarks with docker

### LINKED ISSUE #24: Automate benchmark result aggregation
We need some sort of script that runs all benchmarks automatically, generating the result files, which can then be used by the `make_plots` script to generate fancy graphic results.

### PR DESCRIPTION
**Pull request by vypxl**
Closes #24

### CODE REVIEW

**Comment by vypxl** [comment]
Resolves #24

**Comment by tectrixer** [comment]
The benchmark takes forever and also fails sometimes. Please make a better, more stable version with a lower benchmark count

**Comment by vypxl** [comment]
That is not a problem with this script, but rather our amazing client and servers.

**Comment by umgefahren** [comment]
If you want the issues in the client resolved, please comment on #57.

**Review by umgefahren — APPROVED** [review]

**Review by tectrixer — APPROVED** [review]
Seems good for now, although this should not be the final version

**Comment by umgefahren** [comment]
We'll rewrite some stuff anyway for running on different servers later.

**Review by Zollerboy1 — APPROVED** [review]
Looks good.

**Pull request merged**
