### PR TITLE
Dockerize rust

### PR DESCRIPTION
**Pull request by tectrixer**
I added a Dockerfile for Rust which builds and runs in different containers.

## Usage

To build the image execute:

`docker build -t bench-rust .`

Then you need to create a container:

`docker create --name bench-rust -p 8080:8080 bench-rust`

Then you can start the container like this:

`docker start bench-rust`

For stopping and removing the container execute the following line of code:

`docker stop bench-rust && docker rm bench-rust`

### CODE REVIEW

**Comment by vypxl** [comment]
You got the commit from your other PR in this one :)

**Comment by tectrixer** [comment]
oh, damn, ill try to fix it

**Comment by vypxl** [comment]
Also, please use alpine for the runner and statically-link the executable

**Comment by tectrixer** [comment]
Ok, then ill just do it again with a different branch and delete this one

**Comment by tectrixer** [comment]
Just pushed out the new changes, now the Dockerbuild checks whether its on aarch64 or on x86 and then builds the static binary for the system.

The binary then runs in a scratch system, so not even something like `/bin/sh` there and it proves that it is definitely statically linked. Any other improvements?

**Comment by vypxl** [comment]
Looks good, but I would still prefer an alpine runner for the sake of comparability.

**Comment by tectrixer** [comment]
Ok, sure I'll do that soon in DDCA

**Comment by tectrixer** [comment]
@vypxl I now switched to alpine, im now gonna try to resolve the merge conflicts

**Review by vypxl — APPROVED** [review]

**Pull request merged**
